---
driver:
  name: vagrant

platforms:
  - name: ubuntu-16.04
  #- name: ubuntu-18.04

provisioner:
  name: ansible_playbook
  role_name: ansible-role-docker
  ansible_cfg_path: "./tests/ansible.cfg"
  ansible_inventory: "./tests/inventory"
  requirements_path: tests/requirements.yml
  #### general
  ansible_verbose: true
  idempotency_test: true
  diff: true
  #https://github.com/geerlingguy/ansible-role-mysql/issues/212
  sudo_command: sudo -H
  custom_post_install_command: |
    sudo apt install -y python-pip

verifier:
  name: inspec

suites:
  - name: default
    provisioner:
      playbook: "./tests/default/test.yml"
    verifier:
      inspec_tests:
        - path: tests/default/

  - name: docker_version
    provisioner:
      playbook: "./tests/docker_version/test.yml"
    verifier:
      inspec_tests:
        - path: tests/docker_version/
