---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  idempotency_test: True
  hosts: all

platforms:
- name: ubuntu-16.04
  driver_config:
    image: ubuntu:16.04
    platform: ubuntu

- name: ubuntu-18.04
  driver_config:
    image: ubuntu:18.04
    platform: ubuntu

suites:
  - name: default
    provisioner:
      playbook: test/integration/default/default.yml
  - name: docker_version
    provisioner:
      playbook: test/integration/docker_version/default.yml
