---
services: docker

language: ruby
rvm:
  - 2.5

env:
  - PLATFORM: ubuntu-16.04
  - PLATFORM: ubuntu-18.04

addons:
  apt:
    update: True
    packages:
      - ruby-dev

before_script:
  - which kitchen
script:
  # Configure test script so we can run extra tests after playbook is run.
  - bundle exec kitchen converge $PLATFORM
  - bundle exec kitchen verify $PLATFORM
  - bundle exec kitchen destroy $PLATFORM
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
