---
services: docker

language: ruby
rvm:
  - 2.5

addons:
  apt:
    update: True
    packages:
      - ruby-dev

script:
  # Configure test script so we can run extra tests after playbook is run.
  - bundle exec kitchen converge
  - bundle exec kitchen verify
  - bundle exec kitchen destroy
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
