---
services: docker

language: ruby
rvm:
  - 2.3

script:
  # Configure test script so we can run extra tests after playbook is run.
  - bundle install
  - kitchen converge
  - kitchen verify
  - kitchen destroy
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
