language: python
python: "2.7"

services: docker

addons:
  apt:
    update: True
    packages:
      - python-apt

env:
  - ANSIBLE_CONFIG=tests/ansible.cfg ANSIBLE_VERSION=2.4 SUITE=default
  - ANSIBLE_CONFIG=tests/ansible.cfg ANSIBLE_VERSION=2.4 SUITE=docker_version
  - ANSIBLE_CONFIG=tests/ansible.cfg ANSIBLE_VERSION=2.5 SUITE=default
  - ANSIBLE_CONFIG=tests/ansible.cfg ANSIBLE_VERSION=2.5 SUITE=docker_version

before_install:
  - gem install inspec

install:
  - pip install ansible==${ANSIBLE_VERSION}
script:
  - ansible-playbook --syntax-check -i tests/hosts tests/${SUITE}/test.yml
  - ansible-playbook -i tests/hosts tests/${SUITE}/test.yml
  - inspec exec tests/${SUITE}/role_spec.rb
