language: python
python: "2.7"

services: docker

addons:
  apt:
    update: True
    packages:
      - python-apt

env:
  - ANSIBLE_VERSION=2.4 SUITE=default
  - ANSIBLE_VERSION=2.4 SUITE=docker_version
  - ANSIBLE_VERSION=2.5 SUITE=default
  - ANSIBLE_VERSION=2.5 SUITE=docker_version

install:
  - make install
script:
  - make suite=${SUITE} ansible=${ANSIBLE_VERSION}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
