---
- name: ensure aufs driver dependencies are present
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - 'linux-image-extra-{{ ansible_kernel }}'
    - 'linux-image-extra-virtual'
  when:
    - ansible_distribution_version in ['14.04','15.10']
    - ansible_distribution == "Ubuntu"

- name: enable aufs driver support
  modprobe:
    name: aufs
    state: present
