---
- name: ensure lvm2 is present for devicemapper driver
  package:
    name: lvm2
    state: present

- name: ensure logical volume group is configured
  lvg:
    vg: docker
    pvs: "{{ docker_block_device }}"
  when:
    - docker_block_device is defined
    - docker_block_device != ""

- name: ensure thinpool volume is created
  lvol:
    vg: docker
    lv: thinpool size=95%VG
    opts: "--wipesignatures y"
  register: thinpool

- name: ensure thinpoolmeta volume is created
  lvol:
    vg: docker
    lv: thinpoolmeta
    size: 1%VG
    opts: "--wipesignatures y"

- name: ensure volumes are converted to thinpools
  shell: lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  when: thinpool.changed

- name: configure autoextension of thin pools via 'lvm' profile
  copy:
    src: docker-thinpool.profile
    dest: /etc/lvm/profile/docker-thinpool.profile
  register: docker_thinpool_profile
  notify: Restart docker daemon

- name: apply 'lvm' profile
  shell: lvchange --metadataprofile docker-thinpool docker/thinpool
  when: docker_thinpool_profile.changed

- name: ensure /var/lib/docker is present
  file:
    path: /var/lib/docker
    state: directory

- set_fact:
    docker_storage_opts:
      - "dm.thinpooldev=/dev/mapper/docker-thinpool"
      - "dm.use_deferred_removal=true"
      - "dm.use_deferred_deletion=true"
  when: docker_storage_opts is undefined
