---
- assert:
    that: "{{ ansible_kernel | version_compare('4.0.0', '>=')}}"
    msg: "Please upgrade to kernel 4.0.0 or higher."

- name: enable overlay2 driver support
  modprobe:
    name: overlay
    state: present
